### PR TITLE
fix: Repair type error with BaseProvider::request

### PR DESCRIPTION
**Pull request by steveluscher**
The main branch, at the moment, is not buildable, if you delete the package-lock.json.

```
npm install && npm run build
@rollup/plugin-typescript TS2416: Property 'request' in type 'BaseProvider<U>' is not assignable to the same property in base type 'SafeEventEmitterProvider'.
  Type '<T>(args: RequestArguments) => Promise<Maybe<T>>' is not assignable to type '<T, U>(args: RequestArguments<T>) => Promise<Maybe<U>>'.
    Types of parameters 'args' and 'args' are incompatible.
      Type 'RequestArguments<T>' is not assignable to type 'RequestArguments'.
        Types of property 'params' are incompatible.
          Type 'T' is not assignable to type 'Record<string, unknown> | unknown[]'.
            Type 'T' is not assignable to type 'unknown[]'.
```

In this PR, we update the package-lock, and the Typescript types.

### CODE REVIEW

**Comment by metallicalfa** [comment]
@steveluscher  Thanks for the PR. I'm gonna merge it. (I was in the midst of fixing the issue)

**Comment by steveluscher** [comment]
Oh wow, I didn't intend this on being merged yet. It's missing a whole lot of stuff and the build _actually_ doesn't work yet.

**Comment by steveluscher** [comment]
@metallicalfa: the _current_ version of my `repair-type-error-in-baseProvider` branch is the one that fixes it!

**Comment by steveluscher** [comment]
Fixed in https://github.com/torusresearch/solana-embed/pull/25

**Comment by metallicalfa** [comment]
@steveluscher By bad. That exchange change was fixing another usage. Hence, i merged it.

**Pull request merged**
